input {
  beats {
    port => 5044
  }
}

filter {
  # Если ваши логи — это JSON, распакуйте их здесь
  # json {
  #   source => "message"
  # }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
    user => "elastic" # если включена безопасность
    password => "changeme"
  }
  stdout { codec => rubydebug } # Для отладки, можно убрать
}